kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
# image: quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
            - name: NFS_SERVER
              value: nfs.dockerlabs.de
            - name: NFS_PATH
              value: /storage/dynamic
      volumes:
        - name: nfs-client-root
          nfs:
            server: nfs.dockerlabs.de
            path: /storage/dynamic
